# main.yml

# Workflow's name
name: Build Electron App For Win/Mac

# Workflow's trigger
on: 
  push:
    tags:
      - "v*.*.*"

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron app

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [windows-2019, macos-latest, ubuntu-latest]
        node-version: [14.x]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      # step3: npm install
      - name: npm install
        run: |
          npm install

      # step4: build app for mac/win
      - name: build app
        run: |
          if [[ "$MATRIX_OS" == "windows-2019" ]]; then
            npm run build:win
          elif [[ "$MATRIX_OS" == "macos-latest" ]]; then
            npm run build:mac
          else
            npm run build:linux
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # step5: cleanup artifacts in build
      - name: cleanup artifacts
        run: |
          if [[ "$MATRIX_OS" == "windows-2019" ]]; then
            npx rimraf "build/!(*.exe|latest.yml)"
          else
            npx rimraf "build/!(*.dmg|latest.yml)"
          fi

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: build

      # step7: create release
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
